# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkwEQBXDSFwqIfvsQ9SYEg0hLATj5B36
"""



import random

print("Taş, kağıt ve makas oyunumuza hoş geldiniz,\n"
      "kurallarımız çok basit 2 raund kazanan oyunu bitirir eğer ki\n"
      "oynamak istemezseniz 'ÇIKIŞ' yazmanız yeterlidir İyi şanslar!")

def tas_kagit_makas_GULNAZ_EKIN():
    secenekler = ["taş", "kağıt", "makas"]
    evet_hayir = ["evet", "hayır"]
    oyun_numarasi = 1

    while True:
        kullanici_puani = 0
        bilgisayar_puani = 0

        print(f"\nOyun: {oyun_numarasi}. Başarılar dilerim!")

        for tur in range(1, 4):
            print(f"\nTur {tur}: Hazır mısınız?")

            while True:
                kullanici_secimi = input("Lütfen seçiminizi yapın: Taş mı?, Kağıt mı?, Makas mı?: ").lower()

                if kullanici_secimi == "çıkış":
                    print("Çıkış yapılıyor... Yine bekleriz!")
                    return

                if kullanici_secimi not in secenekler:
                    print("Maalesef bu geçerli bir seçim değil. Lütfen 'taş', 'kağıt' ya da 'makas' yazmayı deneyin.")
                else:
                    break

            bilgisayar_secimi = random.choice(secenekler)
            print(f"Bilgisayar {bilgisayar_secimi} seçti.")

            if kullanici_secimi == bilgisayar_secimi:
                print("Bu tur berabere! Ne tesadüf!")
            elif (kullanici_secimi == "taş" and bilgisayar_secimi == "makas") or \
                 (kullanici_secimi == "kağıt" and bilgisayar_secimi == "taş") or \
                 (kullanici_secimi == "makas" and bilgisayar_secimi == "kağıt"):
                print("Tebrikler, bu turu kazandınız!")
                kullanici_puani += 1
            else:
                print("Üzgünüm, bu turu kaybettiniz!")
                bilgisayar_puani += 1

        print("\nOyun Sonucu:")
        print(f"Sizin Puanınız: {kullanici_puani}")
        print(f"Bilgisayarın Puanı: {bilgisayar_puani}")

        if kullanici_puani > bilgisayar_puani:
            print("Harika! Bu oyunu kazandınız!")
        elif bilgisayar_puani > kullanici_puani:
            print("Maalesef, bu oyunu kaybettiniz. Bir dahaki sefere şansınızı tekrar deneyin!")
        else:
            print("Oyun berabere bitti! Gerçekten denk bir mücadeleydi.")

        while True:
            kullanici_cevap = input("\nBir oyun daha oynamak ister misiniz? (Evet/Hayır): ").lower()
            bilgisayar_cevap = random.choice(evet_hayir)
            print(f"Bilgisayarın cevabı: {bilgisayar_cevap.capitalize()}")

            if kullanici_cevap not in evet_hayir:
                print("Bu geçerli bir yanıt değil. Lütfen 'evet' veya 'hayır' yazın.")
            else:
                break

        if kullanici_cevap == "hayır" or bilgisayar_cevap == "hayır":
            print("Oyun sona erdi! Yine bekleriz!")
            break
        else:
            print("Tamam, o zaman bir tur daha oynuyoruz!")
            oyun_numarasi += 1

tas_kagit_makas_GULNAZ_EKIN()